accelerator: cuda       # cuda | cpu
strategy: auto          # dp | ddp | ddp_spawn | xla | deepspeed | fsdp
stage: 2
offload_optimizer: false
offload_parameters: false
devices: 1
precision: 32-true      # 32-true | 32 | 16-mixed | bf16-mixed | 64-true 
num_nodes: 1
seed: 42                # {13|21|42|87|100}
batch_size: 2
grad: 4
max_tokens: 2048
num_shards: 1024