accelerator: cuda       # cuda | cpu
strategy: auto          # dp | ddp | ddp_spawn | xla | deepspeed | fsdp
stage: 2
offload_optimizer: false
offload_parameters: false
num_gpus: 1
precision: 32-true      # 32-true | 32 | 16-mixed | bf16-mixed | 64-true 
num_nodes: 1
seed: 42                # {13|21|42|87|100}
batch_size: 2
grad: 4
max_tokens: 2048
num_shards: 1024
num_workers: 2
epochs: 1               # numbers of epochs
start_epochs: 0         # start epoch for resume training
start_steps: 0          # start steps of start epochs
save_steps: 10000       # save every n steps
eval_steps: 10000       # eval every n steps
save_paths: ./weight    # path to save model
load_weight_path: False # path to load weight of model
decay_lr: true
warmup_iters: 2000
lr_decay_iters: 600000
min_lr: 6e-5