name: pytest and coverage report for Model

on:
  push:
    paths:
      - "src/model/**/*.py"
      - "tests/model/**/*.py"

    branches:
      - "new/pytest-ci"

jobs:
  pytest_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e src/model

      - name: Run pytest with coverage
        run: |
          pytest --cov=src/model tests/model/

      - name: Generate HTML coverage report
        run: |
          pytest --cov-report html --cov=src/model tests/model/

      # - name: Upload coverage report to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     flags: unittests
      #     file: ./coverage.xml
      #     token: ${{ secrets.CODECOV_TOKEN }}
