name: pytest and coverage report for Data

on:
  pull_request:
    paths:
      - "src/data/**/*.py"
      - "tests/data/**/*.py"

    branches:
      - "new/pytest-ci"

jobs:
  pytest_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e src/core
          pip install -e src/data

      - name: Generate HTML coverage report
        run: |
          pytest --cov-report xml --cov=src/data tests/data/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
