name: pytest and coverage report for Evaluation

on:
  pull_request:
    paths:
      - "src/evaluation/**/*.py"
      - "tests/evaluation/**/*.py"

    branches:
      - "main"
  push:
    paths:
      - "src/core/**/*.py"
      - "tests/core/**/*.py"

    branches:
      - "main"

concurrency:
  group: test_evaluation:${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest_and_coverage_evaluation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"] # requires python<=3.9

      - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/model/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e src/core
          pip install -e src/evaluation

      - name: Run Mypy
        run: |
          mypy ./src/evaluation/openthaigpt_pretraining_evaluation

      - name: Generate HTML coverage report
        run: |
          pytest --cov-report xml --cov=src/evaluation tests/evaluation/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
